# Generated by Django 3.0 on 2020-05-14 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=30)),
                ('Name', models.CharField(max_length=20)),
                ('Age', models.IntegerField(choices=[(10, 'Age10'), (20, 'Age20'), (30, 'Age30'), (40, 'Age40')])),
                ('Sex', models.CharField(choices=[('남성', 'Man'), ('여성', 'Woman')], max_length=20)),
                ('Job', models.CharField(max_length=20)),
                ('Height', models.IntegerField()),
                ('Weight', models.IntegerField()),
                ('BMI', models.IntegerField()),
            ],
        ),
    ]
