# Generated by Django 3.0.6 on 2020-05-17 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userWeb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
                ('ExerPart', models.CharField(choices=[('a', 'Part1'), ('b', 'Part2'), ('c', 'Part3'), ('d', 'Part4'), ('e', 'Part5')], max_length=20)),
                ('ExerciseDesc', models.CharField(max_length=200)),
                ('AccuracyLink', models.CharField(max_length=400)),
            ],
        ),
    ]
