# Generated by Django 3.0 on 2020-05-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userWeb', '0002_exercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='YoutubeLink',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='ExerPart',
            field=models.CharField(choices=[('가슴', 'Part1'), ('하체', 'Part2'), ('전신', 'Part3'), ('복부', 'Part4')], max_length=20),
        ),
    ]
