# Generated by Django 3.0 on 2020-05-22 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userWeb', '0003_auto_20200519_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='YoutubeLink',
            field=models.CharField(default='www.youtube.com', max_length=400),
        ),
    ]
