# Generated by Django 3.0 on 2020-05-26 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userWeb', '0005_auto_20200526_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='exerciseList',
        ),
        migrations.AddField(
            model_name='exerciselist',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userWeb.User'),
        ),
        migrations.CreateModel(
            name='ExerciseListElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exerciseName', models.CharField(max_length=40)),
                ('exerciseList', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userWeb.ExerciseList')),
            ],
        ),
    ]
