# Generated by Django 3.0 on 2020-05-31 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userWeb', '0007_auto_20200527_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciselistelement',
            name='exercisePart',
            field=models.CharField(choices=[('가슴', 'Part1'), ('하체', 'Part2'), ('전신', 'Part3'), ('복부', 'Part4')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='BMI',
            field=models.CharField(choices=[('저체중', 'Lowweight'), ('정상', 'Nomalweight'), ('과체중', 'Overweight'), ('비만', 'Obesity')], default='정상', max_length=20),
        ),
    ]
