# Generated by Django 3.0 on 2020-07-06 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userWeb', '0008_auto_20200531_0442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='AccuracyLink',
            field=models.CharField(default='www.youtube.com', max_length=400),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='YoutubeLink',
            field=models.CharField(default='https://www.youtube.com/watch?v=Y3iDSy425gw', max_length=400),
        ),
        migrations.AlterField(
            model_name='user',
            name='Height',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='Weight',
            field=models.FloatField(),
        ),
    ]
