# Generated by Django 3.0 on 2020-07-07 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userWeb', '0009_auto_20200706_0751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='SexM',
            new_name='GenderM',
        ),
        migrations.RenameField(
            model_name='exercise',
            old_name='SexY',
            new_name='GenderY',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Sex',
            new_name='Gender',
        ),
    ]
